name: Docker Auto Deploy (Triggered by CI)

on:
  workflow_run:
    workflows: ["CI/CD"]  # Triggered by successful CI/CD pipeline
    types:
      - completed

jobs:
  dockerize:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: SSH into remote server and deploy containerized application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            echo "Stopping any existing container..."
            docker rm -f smartrpd-app || true

            echo "Removing outdated image..."
            docker rmi smartrpd-app || true

            echo "Navigating to app directory..."
            cd /home/ubuntu/smartrpd_viewer  # Project root

            echo "Building updated Docker image..."
            docker build -t smartrpd-app .

            echo "Starting application container..."
            docker run -d -p 8090:80 --name smartrpd-app smartrpd-app
