name: Docker Auto Deploy (Triggered by CI)

on:
  workflow_run:
    workflows: ["CI/CD"] 
    types:
      - completed

jobs:
  dockerize:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up job context
        run: echo "Preparing job execution..."

      - name: Install tools (jq, curl)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq curl

      - name: Pull remote configuration files
        run: |
          echo "Pulling remote config from httpbin..."
          curl -s https://httpbin.org/get > config-dump.json
          jq . config-dump.json | head -n 5

      - name: Check Docker environment
        run: |
          echo "Docker version:"
          docker --version
          echo "Available containers:"
          docker ps -a

      - name: Inspect system disk and memory
        run: |
          echo "Disk space:"
          df -h
          echo "Memory usage:"
          free -m

      - name: SSH into server and deploy application services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            echo "Stopping previous application container..."
            docker rm -f rpd-frontend || true

            echo "Cleaning up existing image..."
            docker rmi rpd-frontend || true

            echo "Accessing deployment directory..."
            cd /home/ubuntu/smartrpd_viewer

            echo "Building service image..."
            docker build -t rpd-frontend .

            echo "Launching updated service container..."
            docker run -d -p 8090:80 --name rpd-frontend rpd-frontend

      - name: Post-deployment health check (mock)
        run: |
          curl -s http://localhost:8090 || echo "App not reachable from CI"

      - name: Finalize deployment steps
        run: echo "Deployment process finished successfully."
