name: Docker Auto Deploy (Triggered by CI)

on:
  workflow_run:
    workflows: ["CI/CD"] 
    types:
      - completed

jobs:
  deploy-app-service:  
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and deploy application services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}            # Remote server IP
          username: ${{ secrets.EC2_USER }}        # Usually 'ubuntu'
          key: ${{ secrets.EC2_SSH_KEY }}          # PEM file content

          script: |
            echo "Stopping previous application container..."
            docker rm -f rpd-frontend || true

            echo "Cleaning up existing image..."
            docker rmi rpd-frontend || true

            echo "Accessing deployment directory..."
            cd /home/ubuntu/smartrpd_viewer

            echo "Building service image..."
            docker build -t rpd-frontend .

            echo "Launching updated service container..."
            docker run -d -p 8090:80 --name rpd-frontend rpd-frontend
