name: Docker Auto Deploy (Triggered by CI)

on:
  workflow_run:
    workflows: ["CI/CD"] 
    types:
      - completed

jobs:
  dockerize:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Set up job context
        run: echo "Preparing job execution..."

      - name: Install tools (jq, curl)
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq curl

      - name: Pull remote configuration files
        run: |
          echo "Pulling remote config from httpbin..."
          curl -s https://httpbin.org/get > config-dump.json
          jq . config-dump.json | head -n 5

      - name: Check Docker environment
        run: |
          echo "Docker version:"
          docker --version
          echo "Available containers:"
          docker ps -a

      - name: Inspect system disk and memory
        run: |
          echo "Disk space:"
          df -h
          echo "Memory usage:"
          free -m

      - name: SSH into server and deploy application services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST }}
          username: ${{ secrets.GCP_USER }}
          key: ${{ secrets.GCP_SSH_KEY }}

          script: |
            echo "Stopping previous application container..."
            docker rm -f smartrpd-case-service || true

            echo "Cleaning up existing image..."
            docker rmi smartrpd-case-service || true

            echo "Accessing deployment directory..."
            cd ~/smartrpd_viewer      # 或者用 $HOME 变量


            echo "Building service image..."
            docker build -t smartrpd-case-service .

            echo "Launching updated service container..."
            docker run -d -p 8090:80 --name smartrpd-case-service smartrpd-case-service

      - name: Post-deployment health check
        run: |
          curl -s http://localhost:8090 || echo "App not reachable from CI"

      - name: Finalize deployment steps
        run: echo "Deployment process finished successfully."
