name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # 你的 Node.js 版本

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          echo "Running build..."
          npm run build
          echo "Output in dist/:"
          ls -lh dist/ || true
          echo "Contents of css/:"
          ls -lh css/ || true
          echo "Contents of assets/:"
          ls -lh assets/ || true
          echo "Root-level JS:"
          ls -lh *.js || true
          echo "Root-level HTML:"
          ls -lh *.html || true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true
          exclude_assets: |
            .github/**
            .gitignore
            node_modules/**
            Jenkinsfile
            Dockerfile
            README.md
